server:
  port: 8080
spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/my-app?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
  docker:
    compose:
      lifecycle-management: start-only
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      SedeRel1Unique: SEDE_REL1UNIQUE
      SistemaSeguridadRel2Unique: SISTEMA_SEGURIDAD_REL2UNIQUE
      SistemaSeguridadRel3Unique: SISTEMA_SEGURIDAD_REL3UNIQUE
      SistemaSeguridadRel4Unique: SISTEMA_SEGURIDAD_REL4UNIQUE
springdoc:
  pathsToMatch: /api/**


